### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by Krishath** [varlesh/papirus-icon-theme#2]
If it's not a problem for you, we could keep this issue up for any missing icon.

* KOrganizer

**Comment by varlesh** [comment]
Hello )) Could you clarify some points ?
Find files and folders (start menu)  - I do not understand what it was about ?
KRDP - I do not know KRDP. Did you mean KRDC?

**Comment by varlesh** [comment]
I added some icons. Please see commit https://github.com/varlesh/papirus-icon-theme/commit/58806ee1bbca28d92b3fd0a18d1df31281b440a4

**Comment by Krishath** [comment]
Yes, I meant KRDC, sorry! If it's ok with you I'll keep this thread alive with all my discoverings.

**Comment by varlesh** [comment]
KOrganizer added https://github.com/varlesh/papirus-icon-theme/commit/90e6338510b8738e3ba383e14e8de3f9641bb200

**Comment by zuckzappl** [comment]
some suggestions of apps with missing icons:
* KeePassX
* Texmaker
* JabRef
* Boomaga

**Comment by varlesh** [comment]
Ok. KeePassX already added. 
Please , write name icon and applications. For example:
app = KeePassX
icon = keepassx

**Comment by varlesh** [comment]
Added 9eaa37758210d649cda10d9a50ab94092ff8efa0

**Comment by feskyde** [comment]
You will add icons for distributions? (start-here-[distro] or distributor-logo-[distro]).

**Comment by varlesh** [comment]
yes
I'll add start-here-kde

**Comment by feskyde** [comment]
I say if you will add the start-here *for the different distributions* (Arch, Ubuntu, Fedora, Mint, Debian, openSUSE, and such)

**Comment by varlesh** [comment]
Ok. I'll do it soon.

**Comment by feskyde** [comment]
Thanks! :dancer:

**Comment by LukeStonehm** [comment]
Good day sir! I love the icon pack and theme! Very good stuff. 

Could I suggest adding an icon for Android .apk files. Android application package files :smile: 

Thanks again.

**Comment by varlesh** [comment]
d558a59c62d012eb4d57071740b632a96d85fb95

**Comment by LukeStonehm** [comment]
Cool thank you sir!

**Comment by LukeStonehm** [comment]
Good day,

Could you look into making a nice "repository" icon. It's in the system icons. I use this icon to indicate GIT folders on my system :smile: 

Thanks again.

**Comment by varlesh** [comment]
create git and folder-git icons 59533aa1163586272b15f5f3f9a0a517399dd5eb

**Comment by LukeStonehm** [comment]
Jesus... you are damn fast! Thank you very much!
