### ISSUE TITLE
papirus-icon-theme in AUR

### ISSUE THREAD

**Issue by zuckzappl** [varlesh/papirus-icon-theme#3]
Hey, I like your KDE-adaptation of  the paper theme. As you already provide a PKGBUILD (thanks for that), how come that you didn't upload it to the Arch User Repository?

**Comment by varlesh** [comment]
I do not use Arch Linux. Anyone can download on AUR , I do not mind ))

**Comment by horosgrisa** [comment]
@zuckzappl Hi, I use Arch, and I can make PKGBUILD.

**Comment by horosgrisa** [comment]
@zuckzappl https://cloud.udom.tk/index.php/s/vd7iPRMAjcD9nwh
Soon I will upload to AUR

**Comment by varlesh** [comment]
Ok, thx )

**Comment by horosgrisa** [comment]
@zuckzappl @varlesh Now you can install papirus-icon-theme from AUR4. 
https://aur4.archlinux.org/packages/papirus-icon-theme/

**Comment by varlesh** [comment]
Very good :+1:

**Comment by horosgrisa** [comment]
I think that you can close this issue.

**Comment by zuckzappl** [comment]
Thx horosgrisa, I thought about doing it myself, but didn't want to fiddle around with AUR4. And now I don't have to. :)

**Comment by varlesh** [comment]
@horosgrisa 
Hi, i add icons for libreoffice. Please update PKGBUILD
https://github.com/varlesh/papirus-icon-theme/tree/master/papirus/extra-icons/libreoffice

**Comment by horosgrisa** [comment]
@varlesh Yes, move to extra.

**Comment by horosgrisa** [comment]
@varlesh You can create `look-and-feel` package for KDE?

**Comment by varlesh** [comment]
@horosgrisa  
I delete this repository it soon.
And moved all to new repository https://github.com/varlesh/papirus-pack-kde
So it will be more convenient and better.

**Comment by horosgrisa** [comment]
@varlesh Very good, I will update my PKGBUILD's.

**Comment by varlesh** [comment]
Thx )
